#!/usr/bin/env zsh

if [[ $OSTYPE == linux* ]] ; then
    sudo apt update
    sudo apt install -y python3 fzf bat neovim

    curl -sS https://starship.rs/install.sh > ./starship.sh
    sh ./starship.sh --yes
    rm ./starship.sh
fi