#!/usr/bin/env zsh

if (( ! $+commands[python3] )) ; then
    if [[ $OSTYPE == linux* ]] ; then
        if (( $+commands[sudo] )) ; then
            sudo apt install -y python3
        else
            apt install -y python3
        fi
    elif [[ $OSTYPE == darwin* ]] ; then
        brew install python3
    fi
fi
